# Generated by Django 3.1.6 on 2024-05-31 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordentry',
            old_name='hashed_password',
            new_name='encrypted_password',
        ),
    ]
